### ISSUE TITLE
Can't run npm run dev due to missing babel plug-in

### ISSUE THREAD

**Issue by spun-jeremy** [mazipan/bulma-admin-dashboard-template#191]
Hi,

The admin template looks great and I'd like to use it, but unfortunately I've failed to run dev for it on Linux and MacOS, with the following error:

ERROR in ./src/main.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: [BABEL] /Users/jer/Documents/SpeakUnique/bulma-admin-dashboard-template/src/main.js: Could not find plugin "proposal-numeric-separator". Ensure there is an entry in ./available-plugins.js for it.

I've had a look at that available-plugins.js file in node_modules/@babel but I'm not sure about editing it to include this. 

Any information on how to resolve would be great. Thanks.

![image](https://user-images.githubusercontent.com/56347320/81746634-c0e1f980-949e-11ea-8d17-c633919dedfc.png)

**Comment by drfinkus** [comment]
I got past this error following the directions of the 4th answer here: https://stackoverflow.com/questions/60780664/could-not-find-plugin-proposal-numeric-separator

Now, it works, but it runs on 8080 and just returns an empty response.
