### ISSUE TITLE
Add contribution guide

### ISSUE THREAD

**Issue by mazipan** [mazipan/bulma-admin-dashboard-template#2]
I need contribution guide in this repo.
You can see the sample contribution guide from this pull request
https://github.com/mazipan/vue-currency-filter/pull/5/files

Thanks for your help 🎉🎉🎉

**Comment by ilimugur** [comment]
I can take this one, if it isn't already taken. Could you highlight any differences to be made to the sample guide you provided, though?

**Comment by mazipan** [comment]
Should be same I think

**Comment by ilimugur** [comment]
On it.

**Comment by ilimugur** [comment]
I added the CONTRIBUTING.md, and updated the links to reflect this repo. Also referenced it in README.md.
