### ISSUE TITLE
Add capability to hide/show sidebar

### ISSUE THREAD

**Issue by mazipan** [mazipan/bulma-admin-dashboard-template#202]
It's nice if we have a small hamburger menu like any other template admin to hide/show the sidebar.

**Comment by dennib** [comment]
Tryed something with [#203](https://github.com/mazipan/bulma-admin-dashboard-template/pull/203) :)

**Comment by mazipan** [comment]
Still need to re-check...
Especially on the button placement for toggling.

I will close for now.
