### ISSUE TITLE
Sidebar shold be sticky on the left

### ISSUE THREAD

**Issue by mazipan** [mazipan/bulma-admin-dashboard-template#207]
On the desktop, sidebar should be sticky with height 100vh

![Screen Shot 2020-10-08 at 19 49 07](https://user-images.githubusercontent.com/7221389/95460634-64c4c800-099f-11eb-9b86-0fd9e6c68b2c.png)

**Comment by BhupaliRane** [comment]
Can I work on this, I can fix this issue
